# Generated by Django 4.0 on 2025-11-28 13:46

import base.models.order_models
import base.models.reserve_models
import base.models.shop_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=base.models.shop_models.create_id, max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('is_paymentstatus', models.BooleanField(default=False, verbose_name='有料会員')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除状態')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='カテゴリー名')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='スラッグ')),
            ],
        ),
        migrations.CreateModel(
            name='Regular_holidays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_holiday', models.BooleanField(default=False, verbose_name='定休日設定')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='タグ名')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='スラッグ')),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='管理コード')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='曜日')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.user')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='名前')),
                ('zipcode', models.CharField(blank=True, default='', max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, default='', max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='市町村')),
                ('address1', models.CharField(blank=True, default='', max_length=50, verbose_name='住所1 丁目・番地・号')),
                ('address2', models.CharField(blank=True, default='', max_length=50, verbose_name='住所2 マンション・アパート名')),
                ('tel', models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(default=base.models.shop_models.create_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('mail', models.CharField(blank=True, default='', max_length=255, verbose_name='メールアドレス')),
                ('zipcode', models.CharField(blank=True, default='', max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='住所')),
                ('tel', models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('price', models.CharField(blank=True, default='', max_length=50, verbose_name='平均予算')),
                ('seating_capacity', models.TextField(blank=True, default='', verbose_name='席数')),
                ('opening_hours', models.TextField(blank=True, default='', verbose_name='営業時間・ラストオーダーの案内')),
                ('holiday', models.TextField(blank=True, default='', verbose_name='定休日の案内')),
                ('reserve_start_time', models.TimeField(blank=True, default='', verbose_name='予約開始時間')),
                ('reserve_end_time', models.TimeField(blank=True, default='', verbose_name='予約終了時間')),
                ('image', models.ImageField(blank=True, default='', upload_to=base.models.shop_models.upload_image_to)),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('regular_holidays', models.ManyToManyField(related_name='shops_set_holidays', through='base.Regular_holidays', to='base.Weekday')),
                ('tags', models.ManyToManyField(to='base.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='評価点')),
                ('content', models.TextField(blank=True, default='', verbose_name='レビュー内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shop', verbose_name='レビュー店舗')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user', verbose_name='レビューユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.CharField(default=base.models.reserve_models.custom_timestamp_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('reserved_time', models.DateTimeField(verbose_name='予約日時')),
                ('number_of_people', models.PositiveSmallIntegerField(verbose_name='予約人数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shop', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user', verbose_name='ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='regular_holidays',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_holidays_relationship', to='base.shop'),
        ),
        migrations.AddField(
            model_name='regular_holidays',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.weekday'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=base.models.order_models.custom_timestamp_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('tax_included', models.PositiveIntegerField(default=0)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regular_holidays',
            unique_together={('shop', 'weekday')},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shop', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user', verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'shop')},
            },
        ),
    ]
