# Generated by Django 4.0 on 2025-11-25 07:18

import base.models.shop_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='index',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=base.models.shop_models.create_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
