# Generated by Django 4.0 on 2025-11-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_index_weekday_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='category_id',
            new_name='category',
        ),
    ]
