# Generated by Django 4.0 on 2025-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '★'), (2, '★'), (3, '★'), (4, '★'), (5, '★')], null=True, verbose_name='評価'),
        ),
    ]
